force-app/main/default/objects/Case/fields/Case_Plan__c.field-meta.xml
<CustomField>
    <fullName>Case_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Plan</label>
    <referenceTo>Case_Plan__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Plan__c/Case_Plan__c.object-meta.xml
<CustomObject>
    <label>Case Plan</label>
    <nameField>
        <label>Case Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Step__c/Plan_Step__c.object-meta.xml
<CustomObject>
    <label>Plan Step</label>
    <nameField>
        <label>Plan Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Step__c/fields/Case_Plan__c.field-meta.xml
<CustomField>
    <fullName>Case_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Plan</label>
    <referenceTo>Case_Plan__c</referenceTo>
    <relationshipLabel>Plan Steps</relationshipLabel>
    <relationshipName>Plan_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/caseMgmt_CasePlanControllerTest.cls
@isTest(SeeAllData=true)
private class caseMgmt_CasePlanControllerTest {
    public static testMethod void testf0rCallout(){
        Test.setMock(HTTPCalloutMock.class, new MockHttpResponseGenrator());
        
        Id caseID = [Select Id from Case Limit 1].Id;
        CaseMgmt_CasePlanController.CaseManager caseManagerData = CaseMgmt_CasePlanController.manageCase(caseID);
        List<RecordType> rcType = new List<RecordType>();
        rcType = [SELECT Id, DeveloperName FROM RecordType WHERE SObjectType = 'Case'];
        List<Case_Plan__c> casePlanList = [Select Id from Case_Plan__c];
        Plan_Step__c ps = new Plan_Step__c();
        ps.Name = 'Test Plan';
        ps.Case_Plan__c = casePlanList[0].Id;
        insert ps;
        Case caseInsertObj = new Case();
        caseInsertObj.Subject = 'Test';
        caseInsertObj.Case_Plan__c = casePlanList[0].Id;
        caseInsertObj.RecordTypeId = rcType[0].Id;
        insert caseInsertObj;
        List<String> listOfArgument= new List<String>();
        System.debug('SD : ' + rcType[0].Id);
        listOfArgument.add(rcType[0].Id);
        List<String> cm = CaseMgmt_CasePlanController.fetchRecordTypePicklistValue(listOfArgument);
    }
}