force-app/main/default/objects/Case/fields/Case_Plan__c.field-meta.xml
<CustomField>
    <fullName>Case_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Plan</label>
    <referenceTo>Case_Plan__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Plan__c/Case_Plan__c.object-meta.xml
<CustomObject>
    <label>Case Plan</label>
    <nameField>
        <label>Case Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Plan_Record_Type__c/Case_Plan_Record_Type__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Case Plan &amp; Record Type</label>
</CustomObject>

force-app/main/default/objects/Case_Plan_Record_Type__c/fields/Case_Plan__c.field-meta.xml
<CustomField>
    <fullName>Case_Plan__c</fullName>
    <label>Case Plan</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Plan_Record_Type__c/fields/Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Record_Type__c</fullName>
    <label>Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Step__c/Case_Step__c.object-meta.xml
<CustomObject>
    <label>Case Step</label>
    <nameField>
        <label>Case Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Step__c/fields/Associated_Status__c.field-meta.xml
<CustomField>
    <fullName>Associated_Status__c</fullName>
    <label>Associated Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Step__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Steps</relationshipLabel>
    <relationshipName>Case_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Step__c/fields/Plan_Step__c.field-meta.xml
<CustomField>
    <fullName>Plan_Step__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan Step</label>
    <referenceTo>Plan_Step__c</referenceTo>
    <relationshipLabel>Case Steps</relationshipLabel>
    <relationshipName>Case_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Step__c/fields/PlanStepOrder__c.field-meta.xml
<CustomField>
    <fullName>PlanStepOrder__c</fullName>
    <label>PlanStepOrderDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Plan_Step__c/Plan_Step__c.object-meta.xml
<CustomObject>
    <label>Plan Step</label>
    <nameField>
        <label>Plan Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Step__c/fields/Associate_Case_Status__c.field-meta.xml
<CustomField>
    <fullName>Associate_Case_Status__c</fullName>
    <label>Associated Case Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plan_Step__c/fields/Case_Plan__c.field-meta.xml
<CustomField>
    <fullName>Case_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Plan</label>
    <referenceTo>Case_Plan__c</referenceTo>
    <relationshipLabel>Plan Steps</relationshipLabel>
    <relationshipName>Plan_Steps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/generateCaseStepsHandler.cls
/**
  Handler class for generateCaseSteps apex trigger
  when new case is created or existing one updated it will add
  and update the case with new or existing case step
*/

public with sharing class generateCaseStepsHandler {


    public static void beforeInsertAndUpdate(List<Case> newList, Map<Id, Case> oldMap) {
        updateCasePlanWhenInsertAndUpdate(newList, oldMap);
    }
    public static void afterInsertAndUpdate(List<Case> newList, Map<Id, Case> oldMap) {
        updateCaseSteps(newList, oldMap);
    }
    public static void updateCaseSteps(List<Case> newList, Map<Id, Case> oldMap) {
        Set<Id> casePlanIdSet = new Set<Id>();
        Map<Id, List<Plan_Step__c>> mapOfCasePlanIdWithPlanSteps = new Map<Id, List<Plan_Step__c>>();
        List<Case_Step__c> listOfCaseSteptoBeCreated = new List<Case_Step__c>();
        Set<Id> CaseIdSet = new Set<Id>();
        Case_Step__c caseStepObj;
        List<Case> newListCase = new List<Case>();
        List<Case_Step__c> caseStepToBeDeleted = new List<Case_Step__c>();

        for (Case caseObj : newList) {
            if(oldMap == null){
                casePlanIdSet.add(caseObj.Case_Plan__c);
                newListCase.add(caseObj);
            }else{
                if(oldMap.get(caseObj.Id).RecordTypeId != caseObj.RecordTypeId){
                    casePlanIdSet.add(caseObj.Case_Plan__c);
                    newListCase.add(caseObj);
                    CaseIdSet.add(caseObj.Id);
                }
            }
        }

        for(Case_Step__c caseStepLoopObj : [Select Id from Case_Step__c Where Case__c IN : CaseIdSet]){
            caseStepToBeDeleted.add(caseStepLoopObj);
        }

        if(caseStepToBeDeleted.size() > 0){
            delete caseStepToBeDeleted;
        }

        for (Plan_Step__c planStep : [Select Id, Name,Case_Plan__c, Associate_Case_Status__c,CreatedDate from Plan_Step__c Where Case_Plan__c IN :casePlanIdSet]) {
            if (mapOfCasePlanIdWithPlanSteps.containsKey(planStep.Case_Plan__c)) {
                mapOfCasePlanIdWithPlanSteps.get(planStep.Case_Plan__c).add(planStep);
            } else {
                mapOfCasePlanIdWithPlanSteps.put(planStep.Case_Plan__c, new List<Plan_Step__c>{
                        planStep
                });
            }
        }

        for (Case caseobj : newListCase){
            for(Id casePlanId : mapOfCasePlanIdWithPlanSteps.keySet()){
                if(casePlanId == caseobj.Case_Plan__c){
                    for(Plan_Step__c planStep : mapOfCasePlanIdWithPlanSteps.get(casePlanId)){
                        caseStepObj = new Case_Step__c();
                        caseStepObj.Name = planStep.Name;
                        caseStepObj.Case__c = caseobj.Id;
                        caseStepObj.Plan_Step__c = planStep.Id;
                        caseStepObj.PlanStepOrder__c = planStep.CreatedDate;
                        caseStepObj.Associated_Status__c = planStep.Associate_Case_Status__c;
                        listOfCaseSteptoBeCreated.add(caseStepObj);
                    }
                }
            }
        }

        if(listOfCaseSteptoBeCreated.size() > 0){
            insert listOfCaseSteptoBeCreated;
        }



    }
    public static void updateCasePlanWhenInsertAndUpdate(List<Case> newList, Map<Id, Case> oldMap) {
        Map<String, String> mapOfActiveCasePlanWithRecordType = new Map<String, String>();
        List<RecordType> recordTypelist = new List<RecordType>();
        Map<String, String> mapOfCasePlanNameWithId = new Map<String, String>();
        for (Case_Plan_Record_Type__c casePlanSupportProcess : [Select Id, Case_Plan__c, Record_Type__c From Case_Plan_Record_Type__c]) {
            mapOfActiveCasePlanWithRecordType.put(casePlanSupportProcess.Record_Type__c, casePlanSupportProcess.Case_Plan__c);
        }
        for (RecordType recordTypeRec : [Select Id, DeveloperName from RecordType where SobjectType = 'Case']) {
            recordTypelist.add(recordTypeRec);
        }
        for (Case_Plan__c casePlan : [Select Id, Name from Case_Plan__c Where Name IN :mapOfActiveCasePlanWithRecordType.values()]) {
            mapOfCasePlanNameWithId.put(casePlan.Name, casePlan.Id);
        }
        if (oldMap == null) {
            for (case casObj : newList) {
                if (casObj.RecordTypeId != null) {
                    for (RecordType recObj : recordTypelist) {
                        if (casObj.RecordTypeId == recObj.Id) {
                            casObj.Case_Plan__c = mapOfCasePlanNameWithId.get(mapOfActiveCasePlanWithRecordType.get(recObj.DeveloperName));
                        }
                    }

                }
            }
        } else {
            for (Id oldCaseid : oldMap.keySet()) {
                for (Case caseObj : newList) {
                    if (caseObj.RecordTypeId != oldMap.get(oldCaseid).RecordTypeId) {
                        for (RecordType recObj : recordTypelist) {
                            if (caseObj.RecordTypeId == recObj.Id) {
                                caseObj.Case_Plan__c = mapOfCasePlanNameWithId.get(mapOfActiveCasePlanWithRecordType.get(recObj.DeveloperName));
                            }
                        }
                    }
                }
            }

        }
    }


}