force-app/main/default/objects/AP_Approver__c/fields/Approval_Process_Step_Definition__c.field-meta.xml
<CustomField>
    <fullName>Approval_Process_Step_Definition__c</fullName>
    <label>Approval Process Step Definition</label>
    <referenceTo>ApprovalProcessStepDefinition__c</referenceTo>
    <relationshipLabel>AP_Approvers</relationshipLabel>
    <relationshipName>AP_Approvers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AP_Approver__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Combined with the specified name, this identifies an assigned approver. Valid values are:
adhoc—The approver for the step must be selected manually. For the first step, the submitter selects the approver. For the second and later steps, the approver for the previous step selects the approver. For this value, exclude the name field.
user—A user in your organization. For this value, enter a username for the name field.
userHierarchyField—A user specified in a standard or custom user hierarchy field, such as the standard Manager field. For this value, exclude the name field. The user hierarchy field must be defined in the nextAutomatedApprovers for the approval process.
relatedUserField—A user specified in a user lookup field on the submitted record, such as the Last Modified By field. For this value, enter the name of the user lookup field for the name field.
queue—Automatically assign to a queue. For this value, enter the name of the queue for the name field.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adhoc</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>UserHierarchyField</fullName>
            </value>
            <value>
                <fullName>RelatedUserField</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ManageStepApprovers.cls
global with sharing class ManageStepApprovers {

    public static String addStepApprover(Id userOrGroupID, Id approvalStepDefinitionId, String type) {
        AP_Approver__c newApprover = new AP_Approver__c(
                Name = userOrGroupID,
                Approval_Process_Step_Definition__c = approvalStepDefinitionId,
                Type__c = type);
        try {
            insert newApprover;
            return JSON.serialize(newApprover);
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
    public static String removeStepApprover(Id userOrGroupID, Id approvalStepDefinitionId) {
        try {
            delete [SELECT Id FROM AP_Approver__c WHERE Name = :userOrGroupID AND Approval_Process_Step_Definition__c = :approvalStepDefinitionId];
            return 'SUCCESS';
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
    public static String getExistingShares(String approvalStepDefinitionId) {
        return JSON.serialize([SELECT Id, Name, Type__c FROM AP_Approver__c WHERE Approval_Process_Step_Definition__c =: approvalStepDefinitionId]);
    }
    public static List<ListBuilderController.ButtonSetting> getSupportedButtons() {
        List<ListBuilderController.ButtonSetting> supportedButtonSettings = new List<ListBuilderController.ButtonSetting>();
        supportedButtonSettings.add(new ListBuilderController.ButtonSetting('Add',new ListBuilderController.ButtonMatchingRule(ListBuilderController.MatchingAction.EXISTS)));
        supportedButtonSettings.add(new ListBuilderController.ButtonSetting('Remove',new ListBuilderController.ButtonMatchingRule(ListBuilderController.MatchingAction.NOTEXISTS)));
        return supportedButtonSettings;
    }


}