force-app/main/default/objects/ApprovalProcessDefinition__c/ApprovalProcessDefinition__c.object-meta.xml
<CustomObject>
    <label>ApprovalProcessDefinition</label>
    <nameField>
        <label>ApprovalProcessDefinition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApprovalProcessDefinitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApprovalProcessStepDefinition__c/ApprovalProcessStepDefinition__c.object-meta.xml
<CustomObject>
    <label>ApprovalProcessStepDefinition</label>
    <nameField>
        <label>ApprovalProcessStepDefinition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApprovalProcessStepDefinitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApprovalProcessStepDefinition__c/fields/ApprovalProcessDefinition__c.field-meta.xml
<CustomField>
    <fullName>ApprovalProcessDefinition__c</fullName>
    <label>ApprovalProcessDefinition</label>
    <referenceTo>ApprovalProcessDefinition__c</referenceTo>
    <relationshipLabel>Approval Process Step Definitions</relationshipLabel>
    <relationshipName>ApprovalProcessStepDefinitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ApprovalProcessStepDefinition__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Order</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ManageApprovalSteps.cls
global with sharing class ManageApprovalSteps {

    @AuraEnabled(cacheable=true)
    public static List<SearchUtils.Member> getApprovalProcessSteps(Id approvalProcessId) {
        List<ApprovalProcessStepDefinition__c> steps = [SELECT Id, Name FROM ApprovalProcessStepDefinition__c WHERE ApprovalProcessDefinition__c = :approvalProcessId ORDER BY Order__c ASC];
        List<SearchUtils.Member> members = new List<SearchUtils.Member>();
        for (ApprovalProcessStepDefinition__c step : steps) {
            members.add(new SearchUtils.Member(step.Name, step.Id));
        }

        return members;
    }

    @AuraEnabled
    public static void saveApprovalSteps(List<ApprovalProcessStepDefinition__c> appSteps) {
        update appSteps;
    }
}