force-app/main/default/objects/ApprovalInstanceHistory__c/ApprovalInstanceHistory__c.object-meta.xml
<CustomObject>
    <label>AP_ApprovalInstanceHistoryItem</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ApprovalInstanceHistory Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AP_ApprovalInstanceHistoryItems</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApprovalInstanceHistory__c/fields/Approval_Process_Instance__c.field-meta.xml
<CustomField>
    <fullName>Approval_Process_Instance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Process Instance</label>
    <referenceTo>ApprovalProcessInstance__c</referenceTo>
    <relationshipLabel>AP_ApprovalInstanceHistoryItems</relationshipLabel>
    <relationshipName>AP_ApprovalInstanceHistoryItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApprovalInstanceHistory__c/fields/Assigned_User__c.field-meta.xml
<CustomField>
    <fullName>Assigned_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>AP_ApprovalInstanceHistoryItems</relationshipLabel>
    <relationshipName>AP_ApprovalInstanceHistoryItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApprovalInstanceHistory__c/fields/Original_User__c.field-meta.xml
<CustomField>
    <fullName>Original_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Original User</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>AP_ApprovalInstanceHistoryItems (Original User)</relationshipLabel>
    <relationshipName>AP_ApprovalInstanceHistoryItems1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ApprovalProcessHelper.cls
public with sharing class ApprovalProcessHelper {
    @AuraEnabled(cacheable=true)
    public static String getApprovalProcessHistory(Id processInstanceId) {
        System.debug('querying for approval process history');
        List<ApprovalInstanceHistory__c> historyItems = [
                SELECT Id, CreatedDate, Comments__c, Status__c, Original_User__c,Original_User__r.Name, Assigned_User__c, Assigned_User__r.Name
                FROM ApprovalInstanceHistory__c
                WHERE Approval_Process_Instance__c = :processInstanceId
        ];


      
        return JSON.serialize(historyItems);
    }
}