force-app/main/default/objects/AP_AllowedSubmitter__c/AP_AllowedSubmitter__c.object-meta.xml
<CustomObject>
    <label>AP_AllowedSubmitter</label>
    <nameField>
        <label>AP_AllowedSubmitters Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP_AllowedSubmitters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AP_AllowedSubmitter__c/fields/Parent_Approval_Process_Definition__c.field-meta.xml
<CustomField>
    <fullName>Parent_Approval_Process_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Approval Process Definition</label>
    <referenceTo>ApprovalProcessDefinition__c</referenceTo>
    <relationshipLabel>AP_AllowedSubmitters (Parent Approval Process Definition)</relationshipLabel>
    <relationshipName>AP_AllowedSubmitters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApprovalProcessDefinition__c/ApprovalProcessDefinition__c.object-meta.xml
<CustomObject>
    <label>ApprovalProcessDefinition</label>
    <nameField>
        <label>ApprovalProcessDefinition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApprovalProcessDefinitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApprovalProcessDefinition__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ApprovalProcessStepDefinition__c/ApprovalProcessStepDefinition__c.object-meta.xml
<CustomObject>
    <label>ApprovalProcessStepDefinition</label>
    <nameField>
        <label>ApprovalProcessStepDefinition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApprovalProcessStepDefinitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ApprovalProcessStepDefinition__c/fields/ApprovalProcessDefinition__c.field-meta.xml
<CustomField>
    <fullName>ApprovalProcessDefinition__c</fullName>
    <label>ApprovalProcessDefinition</label>
    <referenceTo>ApprovalProcessDefinition__c</referenceTo>
    <relationshipLabel>Approval Process Step Definitions</relationshipLabel>
    <relationshipName>ApprovalProcessStepDefinitions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Approver__c/Approver__c.object-meta.xml
<CustomObject>
    <label>AP_Approver</label>
    <nameField>
        <label>AP_Approver Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP_Approvers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Approver__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Combined with the specified name, this identifies an assigned approver. Valid values are:
adhoc—The approver for the step must be selected manually. For the first step, the submitter selects the approver. For the second and later steps, the approver for the previous step selects the approver. For this value, exclude the name field.
user—A user in your organization. For this value, enter a username for the name field.
userHierarchyField—A user specified in a standard or custom user hierarchy field, such as the standard Manager field. For this value, exclude the name field. The user hierarchy field must be defined in the nextAutomatedApprovers for the approval process.
relatedUserField—A user specified in a user lookup field on the submitted record, such as the Last Modified By field. For this value, enter the name of the user lookup field for the name field.
queue—Automatically assign to a queue. For this value, enter the name of the queue for the name field.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adhoc</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>UserHierarchyField</fullName>
            </value>
            <value>
                <fullName>RelatedUserField</fullName>
            </value>
            <value>
                <fullName>Queue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GenerateTestRecords.cls
public with sharing class GenerateTestRecords {
  
    @InvocableMethod
    public static List<Results> generate(List<Requests> requestList) {
        ApprovalProcessDefinition__c curAPD = generateApprovalProcessDefinition1();
        ApprovalProcessStepDefinition__c curAPStep = generateApprovalProcessStepDefinition(curAPD.Id, 'Step 1');
         generateApprover(curAPStep.Id, 'mikeManager@aof.org', 'User');

        curAPStep = generateApprovalProcessStepDefinition(curAPD.Id, 'Step 2');
        generateApprover(curAPStep.Id, 'dianneDirector@aof.org', 'User');


        //Create a Results object to hold the return values
        Results response = new Results();

        //add the return values to the Results object
 
        
        //Wrap the Results object in a List container (an extra step added to allow this interface to also support bulkification)
        List<Results> responseWrapper= new List<Results>();
        responseWrapper.add(response);
        return responseWrapper;
    }

    public static ApprovalProcessDefinition__c generateApprovalProcessDefinition1() {
        ApprovalProcessDefinition__c curAPD = new ApprovalProcessDefinition__c();
        curAPD.Label__c = 'testDef1';
        insert curAPD;

        //ApprovalProcessStepDefinition__c[] APsteps = new ApprovalProcessStepDefinition__c();
        curAPD = [SELECT Id FROM ApprovalProcessDefinition__c WHERE Label__c='testDef1'];
        generateApprovalSubmitter(curAPD.Id);
        
        return curAPD;
    }

    public static void generateApprovalSubmitter (String curAPD_Id) {
        AP_AllowedSubmitter__c curSubmitter = new AP_AllowedSubmitter__c();
        curSubmitter.Parent_Approval_Process_Definition__c = curAPD_Id;
        curSubmitter.Type__c = 'User';
        curSubmitter.Name = UserInfo.getUserId();
        insert curSubmitter;
    }
     


    public static ApprovalProcessStepDefinition__c generateApprovalProcessStepDefinition(String APD_Id, String Label) {
        ApprovalProcessStepDefinition__c step = new ApprovalProcessStepDefinition__c();
        step.ApprovalProcessDefinition__c = APD_Id;
        step.Label__c = Label;
        insert step;

        step = [SELECT Id FROM ApprovalProcessStepDefinition__c WHERE Label__c = :Label];
        return step;
    }

     public static void generateApprover (String curAPStepId, String Name, String Type) {
        Approver__c approver = new Approver__c();
        approver.Approval_Process_Step_Definition__c = curAPStepId;
        approver.Name = Name;
        approver.Type__c = Type;
        insert approver;
    } 

    public class Requests {

      @InvocableVariable
      public String input; //unused so far
        
    }
    
    public class Results {
     
      @InvocableVariable
      public String output; //unused so far

    }
}